version: '3'

services:

  dependency-track:
    image: 'owasp/dependency-track'
    deploy:
      resources:
        limits:
          memory: 12288m
        reservations:
          memory: 8192m
      restart_policy:
        condition: on-failure
    ports:
      - '80:8080'
    volumes:
      - dependency-track:/data

  vault:
    image: "vault"
    environment:
      VAULT_ADDR: http://127.0.0.1:8300
    ports:
      - "8300:8200"

  jenkins:
    # See https://github.com/jenkinsci/docker for more options
    image: jenkins/jenkins:lts
    volumes:
      - jenkins_data:/var/jenkins_home
    networks:
      - devsecops
    ports:
      - '8080:8080'
      - '50000:50000'
    environment:
      JAVA_OPTS: '-Dhudson.footerURL=https://uzakov.io'


  sonarqube:
    image: sonarqube:7.7-community
    networks:
      - devsecops
    ports:
      - '9000:9000'
    environment:
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=sonar
      - sonar.jdbc.url=jdbc:postgresql://db:5432/sonar

  db:
    image: postgres
    networks:
      - devsecops
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

networks:
  devsecops :
    driver: bridge

volumes:
  dependency-track:
  jenkins_data:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  postgresql:
  postgresql_data: